# 行列
array型を使うとlistでは使えない様々な機能を利用することができます．ただし，listとは挙動が変わっている関数もあるので注意が必要です．

In [1]:
# リストからarrayを生成
import numpy as np
a = np.array([1,2,3])

print( a )

[1 2 3]


In [2]:
# リストから二次元arrayを生成
import numpy as np
a = np.array(
    [[1,2,3],
     [4,5,6],
     [7,8,9]])

print( a )

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# 0～9の要素を持った一次元arrayの生成
import numpy as np
a = np.arange(9)

print( a )

[0 1 2 3 4 5 6 7 8]


In [4]:
# 0～9の要素を持った一次元arrayを3×3の二次元arrayに変換
import numpy as np
a = np.arange(9)
b = a.reshape( (3,3) )

print( b )

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# 二次元arrayの要素を一列（１次元）に並べる
import numpy as np
a = np.arange(9).reshape( (3,3) )
b = a.flatten()

print( b )

[0 1 2 3 4 5 6 7 8]


In [6]:
# arrayの要素に定数を足す
import numpy as np
a = np.arange(9)
a = a.reshape( (3,3) )

b = a + 100 

print( b )

[[100 101 102]
 [103 104 105]
 [106 107 108]]


In [7]:
# 2つのarrayの要素同士の足し算
import numpy as np
a = np.arange(9)
a = a.reshape( (3,3) )

b = np.arange(100,109)
b = b.reshape( (3,3) )

c = a + b

print( a )
print( "+" )
print( b )
print( "=" )
print( c )

[[0 1 2]
 [3 4 5]
 [6 7 8]]
+
[[100 101 102]
 [103 104 105]
 [106 107 108]]
=
[[100 102 104]
 [106 108 110]
 [112 114 116]]


In [8]:
# 2つのarrayの要素同士の掛け算（アダマール積）
import numpy as np
a = np.arange(9)
a = a.reshape( (3,3) )

b = np.arange(100,109)
b = b.reshape( (3,3) )

c = a * b

print( a )
print( "*" )
print( b )
print( "=" )
print( c )

[[0 1 2]
 [3 4 5]
 [6 7 8]]
*
[[100 101 102]
 [103 104 105]
 [106 107 108]]
=
[[  0 101 204]
 [309 416 525]
 [636 749 864]]


In [9]:
# 2つのarrayの行列の掛け算
import numpy as np
a = np.arange(3)
a = a.reshape( (3,1) )

b = np.arange(100,103)
b = b.reshape( (1,3) )

c = a * b

print( a )
print( "*" )
print( b )
print( "=" )
print( c )

[[0]
 [1]
 [2]]
*
[[100 101 102]]
=
[[  0   0   0]
 [100 101 102]
 [200 202 204]]


In [12]:
# arrayの行方向の合計，列方向の合計，全ての要素の合計を計算
import numpy as np
a = np.arange(9).reshape( (3,3) )

print( a )
print( "----" )
print( "rows: ", np.sum(a, 1) )
print( "cols: ", np.sum(a, 0) )
print( "total: ", np.sum(a) )

[[0 1 2]
 [3 4 5]
 [6 7 8]]
----
rows:  [ 3 12 21]
cols:  [ 9 12 15]
total:  36


In [13]:
# arrayの行方向の平均，列方向の平均，全ての要素の平均を計算
import numpy as np
a = np.arange(9).reshape( (3,3) )

print( a )
print( "----" )
print( "rows: ", np.mean(a, 1) )
print( "cols: ", np.mean(a, 0) )
print( "total: ", np.mean(a) )

[[0 1 2]
 [3 4 5]
 [6 7 8]]
----
rows:  [ 1.  4.  7.]
cols:  [ 3.  4.  5.]
total:  4.0


In [14]:
# arrayの一部を取り出し
import numpy as np
a = np.arange(81).reshape( (9,9) )
b = a[3:7,2:5]

print( b )

[[29 30 31]
 [38 39 40]
 [47 48 49]
 [56 57 58]]


In [15]:
# arrayの各要素に対して，sin, con, log, expを一括で計算
import numpy as np
a = np.arange(9).reshape( (3,3) )+0.1

print( "- sin" )
print( np.sin(a) )
print( "- cos" )
print( np.cos(a) )
print( "- log" )
print( np.log(a) )
print( "- exp" )
print( np.exp(a) )

- sin
[[ 0.09983342  0.89120736  0.86320937]
 [ 0.04158066 -0.81827711 -0.92581468]
 [-0.1821625   0.72896904  0.96988981]]
- cos
[[ 0.99500417  0.45359612 -0.5048461 ]
 [-0.99913515 -0.57482395  0.37797774]
 [ 0.98326844  0.68454667 -0.24354415]]
- log
[[-2.30258509  0.09531018  0.74193734]
 [ 1.13140211  1.41098697  1.62924054]
 [ 1.80828877  1.96009478  2.09186406]]
- exp
[[  1.10517092e+00   3.00416602e+00   8.16616991e+00]
 [  2.21979513e+01   6.03402876e+01   1.64021907e+02]
 [  4.45857770e+02   1.21196707e+03   3.29446808e+03]]


In [16]:
# 名前のarray["Taro", "Hanako", "Jiro"]と，テストの点数のarray[95, 80, 90]がある時，
# 点数が90点以上の人を抽出
import numpy as np

names = np.array(["Taro", "Hanako", "Jiro"])
points = np.array([95, 80, 90])

print( names[ points>=90 ] )

['Taro' 'Jiro']


In [17]:
# 特定の条件を満たすarrayのインデックスを取得
import numpy as np
a = np.arange(9).reshape( (3,3) )

y, x = np.where( a>5 )

print( y )
print( x )

[2 2 2]
[0 1 2]


In [18]:
# 行列をファイルに保存
import numpy as np
a = np.arange(9).reshape( (3,3) )

np.savetxt( "npdata.txt", a )

# または
#np.save( "npdata.npy", a )

- np.savetxt
  - テキストファイルで保存します．
  - 値を目で確認することができますが，テキストで表現しきれない情報が欠落したり，ファイルサイズが大きくなります．
- np.save
  - numpy独自の形式（バイナリ）で保存します．
  - 値を目で確認することはできませんが，情報の欠落はなく，ファイルサイズは小さくなります．

In [19]:
# ファイルから行列を読み込み
import numpy as np

a = np.loadtxt( "npdata.txt" )

# または
# a = np.load( "npdata.npy" )

print( a )

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]]
